# Generated by Django 2.1.3 on 2019-02-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_hod_st',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sozd', models.DateField(verbose_name='Дата создания:')),
                ('nazv', models.CharField(max_length=65, verbose_name='Название:')),
                ('text', models.TextField(max_length=865, verbose_name='Oписание:')),
                ('pict1', models.ImageField(blank=True, upload_to='image/hodst', verbose_name='Фото объекта №1')),
                ('pict2', models.ImageField(blank=True, upload_to='image/hodst', verbose_name='Фото объекта №2')),
                ('pict3', models.ImageField(blank=True, upload_to='image/hodst', verbose_name='Фото объекта №3')),
                ('pict4', models.ImageField(blank=True, upload_to='image/hodst', verbose_name='Фото объекта №4')),
            ],
            options={
                'verbose_name_plural': 'Ход строительства',
                'verbose_name': 'Ход строительства',
            },
        ),
        migrations.CreateModel(
            name='stavki_ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sber_proc', models.FloatField(default=0, verbose_name='Процентная ставка(Сбербанк):')),
                ('sber_vznos', models.IntegerField(default=0, verbose_name='Первый взнос(Сбербанк):')),
                ('sber_srok', models.IntegerField(default=0, verbose_name='Срок кредита:(Сбербанк)')),
                ('vtb_proc', models.FloatField(default=0, verbose_name='Процентная ставка(BTБ):')),
                ('vtb_vznos', models.IntegerField(default=0, verbose_name='Первый взнос(BTБ):')),
                ('vtb_srok', models.IntegerField(default=0, verbose_name='Срок кредита(BTБ):')),
                ('alfa_proc', models.FloatField(default=0, verbose_name='Процентная ставка(Альфа-Банк):')),
                ('alfa_vznos', models.IntegerField(default=0, verbose_name='Первый взнос(Альфа-Банк):')),
                ('alfa_srok', models.IntegerField(default=0, verbose_name='Срок кредита(Альфа-Банк):')),
                ('gaz_proc', models.FloatField(default=0, verbose_name='Процентная ставка(ГазПромБанк):')),
                ('gaz_vznos', models.IntegerField(default=0, verbose_name='Первый взнос(ГазПромБанк):')),
                ('gaz_srok', models.IntegerField(default=0, verbose_name='Срок кредита(ГазПромБанк):')),
                ('prom_proc', models.FloatField(default=0, verbose_name='Процентная ставка(ПромсвязьБанк):')),
                ('prom_vznos', models.IntegerField(default=0, verbose_name='Первый взнос(ПромсвязьБанк):')),
                ('prom_srok', models.IntegerField(default=0, verbose_name='Срок кредита(ПромсвязьБанк):')),
                ('sel_proc', models.FloatField(default=0, verbose_name='Процентная ставка(РоссельхозБанк):')),
                ('sel_vznos', models.IntegerField(default=0, verbose_name='Первый взнос(РоссельхозБанк):')),
                ('sel_srok', models.IntegerField(default=0, verbose_name='Срок кредита(РоссельхозБанк):')),
            ],
            options={
                'verbose_name_plural': 'Условия кредитования',
                'verbose_name': 'Условия кредитования',
            },
        ),
    ]
