# Generated by Django 2.1.2 on 2019-01-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stavki_ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_bank', models.CharField(max_length=255, verbose_name='Название банка:')),
                ('proc', models.FloatField(verbose_name='Процентная ставка:')),
                ('vznos', models.IntegerField(verbose_name='Первый взнос:')),
                ('srok', models.IntegerField(verbose_name='Срок кредита:')),
            ],
            options={
                'verbose_name_plural': 'Условия кредитования',
                'verbose_name': 'Условия кредитования',
            },
        ),
    ]
