# Generated by Django 2.1.2 on 2019-01-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stavki_ip',
            name='name_bank',
        ),
        migrations.RemoveField(
            model_name='stavki_ip',
            name='proc',
        ),
        migrations.RemoveField(
            model_name='stavki_ip',
            name='srok',
        ),
        migrations.RemoveField(
            model_name='stavki_ip',
            name='vznos',
        ),
        migrations.AddField(
            model_name='stavki_ip',
            name='alfa_proc',
            field=models.FloatField(default=0, verbose_name='Процентная ставка(Альфа-Банк):'),
        ),
        migrations.AddField(
            model_name='stavki_ip',
            name='alfa_srok',
            field=models.IntegerField(default=0, verbose_name='Срок кредита(Альфа-Банк):'),
        ),
        migrations.AddField(
            model_name='stavki_ip',
            name='alfa_vznos',
            field=models.IntegerField(default=0, verbose_name='Первый взнос(Альфа-Банк):'),
        ),
        migrations.AddField(
            model_name='stavki_ip',
            name='gaz_proc',
            field=models.FloatField(default=0, verbose_name='Процентная ставка(ГазПромБанк):'),
        ),
        migrations.AddField(
            model_name='stavki_ip',
            name='gaz_srok',
            field=models.IntegerField(default=0, verbose_name='Срок кредита(ГазПромБанк):'),
        ),
        migrations.AddField(
            model_name='stavki_ip',
            name='gaz_vznos',
            field=models.IntegerField(default=0, verbose_name='Первый взнос(ГазПромБанк):'),
        ),
        migrations.AddField(
            model_name='stavki_ip',
            name='sber_proc',
            field=models.FloatField(default=0, verbose_name='Процентная ставка(Сбербанк):'),
        ),
        migrations.AddField(
            model_name='stavki_ip',
            name='sber_srok',
            field=models.IntegerField(default=0, verbose_name='Срок кредита:(Сбербанк)'),
        ),
        migrations.AddField(
            model_name='stavki_ip',
            name='sber_vznos',
            field=models.IntegerField(default=0, verbose_name='Первый взнос(Сбербанк):'),
        ),
        migrations.AddField(
            model_name='stavki_ip',
            name='vtb_proc',
            field=models.FloatField(default=0, verbose_name='Процентная ставка(BTБ):'),
        ),
        migrations.AddField(
            model_name='stavki_ip',
            name='vtb_srok',
            field=models.IntegerField(default=0, verbose_name='Срок кредита(BTБ):'),
        ),
        migrations.AddField(
            model_name='stavki_ip',
            name='vtb_vznos',
            field=models.IntegerField(default=0, verbose_name='Первый взнос(BTБ):'),
        ),
    ]
