# Generated by Django 2.1.2 on 2019-01-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190131_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='stavki_ip',
            name='prom_proc',
            field=models.FloatField(default=0, verbose_name='Процентная ставка(ПромсвязьБанк):'),
        ),
        migrations.AddField(
            model_name='stavki_ip',
            name='prom_srok',
            field=models.IntegerField(default=0, verbose_name='Срок кредита(ПромсвязьБанк):'),
        ),
        migrations.AddField(
            model_name='stavki_ip',
            name='prom_vznos',
            field=models.IntegerField(default=0, verbose_name='Первый взнос(ПромсвязьБанк):'),
        ),
        migrations.AddField(
            model_name='stavki_ip',
            name='sel_proc',
            field=models.FloatField(default=0, verbose_name='Процентная ставка(РоссельхозБанк):'),
        ),
        migrations.AddField(
            model_name='stavki_ip',
            name='sel_srok',
            field=models.IntegerField(default=0, verbose_name='Срок кредита(РоссельхозБанк):'),
        ),
        migrations.AddField(
            model_name='stavki_ip',
            name='sel_vznos',
            field=models.IntegerField(default=0, verbose_name='Первый взнос(РоссельхозБанк):'),
        ),
    ]
