# Generated by Django 2.1.2 on 2019-02-01 09:07

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190131_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_hod_st',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sozd', models.DateField(verbose_name='Дата создания:')),
                ('nazv', models.CharField(max_length=65, verbose_name='Название:')),
                ('text', tinymce.models.HTMLField(max_length=365, verbose_name='Oписание:')),
            ],
        ),
    ]
