# Generated by Django 2.1.2 on 2019-02-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_hod_st'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_hod_st',
            options={'verbose_name': 'Ход строительства', 'verbose_name_plural': 'Ход строительства'},
        ),
    ]
