# Generated by Django 2.1.2 on 2019-02-01 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190201_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_hod_st',
            name='date_sozd',
            field=models.DateField(default=datetime.datetime(2019, 2, 1, 12, 17, 1, 554913), verbose_name='Дата создания:'),
        ),
    ]
