# Generated by Django 2.1.2 on 2019-02-01 09:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190201_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_hod_st',
            name='date_sozd',
            field=models.DateField(default=datetime.datetime(2019, 2, 1, 9, 19, 59, 200001, tzinfo=utc), verbose_name='Дата создания:'),
        ),
    ]
