# Generated by Django 2.1.2 on 2019-02-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190201_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_hod_st',
            name='pict1',
            field=models.ImageField(blank=True, upload_to='image/%Y%m%d/hodst', verbose_name='Фото объекта №1'),
        ),
        migrations.AddField(
            model_name='blog_hod_st',
            name='pict2',
            field=models.ImageField(blank=True, upload_to='image/%Y%m%d/hodst', verbose_name='Фото объекта №2'),
        ),
        migrations.AddField(
            model_name='blog_hod_st',
            name='pict3',
            field=models.ImageField(blank=True, upload_to='image/%Y%m%d/hodst', verbose_name='Фото объекта №3'),
        ),
        migrations.AddField(
            model_name='blog_hod_st',
            name='pict4',
            field=models.ImageField(blank=True, upload_to='image/%Y%m%d/hodst', verbose_name='Фото объекта №4'),
        ),
    ]
