# Generated by Django 2.1.2 on 2019-02-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190201_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_hod_st',
            name='text',
            field=models.TextField(max_length=865, verbose_name='Oписание:'),
        ),
    ]
