# Generated by Django 2.1.2 on 2018-11-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zayavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sozd', models.DateField(verbose_name='Дата создания:')),
                ('date_vz', models.DateField(blank=True, null=True, verbose_name='Дата взятия в работу:')),
                ('date_zakr', models.DateField(blank=True, null=True, verbose_name='Дата закрытия заявки:')),
                ('kanal_pr', models.CharField(max_length=35, verbose_name='Источник заявки:')),
                ('name_kl', models.CharField(help_text='Имя', max_length=55, verbose_name='Имя клиента:')),
                ('tel', models.IntegerField(help_text='Ваш номер телефона:', verbose_name='Телефон:')),
                ('text', models.TextField(verbose_name='Описание заявки:')),
                ('status', models.CharField(choices=[('Новая заявка', 'Новая заявка'), ('В работе', 'В работе'), ('Сделка', 'Сделка'), ('Отказ', 'Отказ')], max_length=35, verbose_name='Статус заявки:')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('prizn_pr', models.CharField(default='Нет', max_length=3, verbose_name='Признак просмотра')),
                ('corpus', models.CharField(default='', max_length=55, verbose_name='Корпус:')),
                ('comnat', models.CharField(default='', max_length=55, verbose_name='Кол-во комнат:')),
                ('ploshad', models.IntegerField(default=0, verbose_name='Площадь квартиры:')),
                ('kv_numb', models.IntegerField(default=0, verbose_name='№ квартиры')),
                ('stoimost', models.IntegerField(default=0, verbose_name='Стоимость квартиры:')),
            ],
            options={
                'verbose_name_plural': 'Заявки',
                'verbose_name': 'Заявки',
            },
        ),
    ]
