# Generated by Django 2.1.2 on 2018-10-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zayavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sozd', models.DateField(verbose_name='Дата создания:')),
                ('date_vz', models.DateField(blank=True, null=True, verbose_name='Дата взятия в работу:')),
                ('date_zakr', models.DateField(blank=True, null=True, verbose_name='Дата закрытия заявки:')),
                ('kanal_pr', models.CharField(max_length=35, verbose_name='Источник заявки:')),
                ('name_kl', models.CharField(help_text='Имя', max_length=55, verbose_name='Имя клиента:')),
                ('tel', models.IntegerField(help_text='Телефон', verbose_name='Телефон:')),
                ('text', models.TextField(verbose_name='Описание заявки:')),
                ('status', models.CharField(choices=[('Новая заявка', 'Новая заявка'), ('В работе', 'В работе'), ('Сделка', 'Сделка'), ('Отказ', 'Отказ')], max_length=35, verbose_name='Статус заявки:')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
