# Generated by Django 2.1.2 on 2018-11-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zayavka', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zayavka',
            name='comnat',
        ),
        migrations.RemoveField(
            model_name='zayavka',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='zayavka',
            name='kv_numb',
        ),
        migrations.RemoveField(
            model_name='zayavka',
            name='ploshad',
        ),
        migrations.RemoveField(
            model_name='zayavka',
            name='stoimost',
        ),
    ]
