# Generated by Django 2.1.2 on 2018-10-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayavka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='prizn_pr',
            field=models.CharField(default='Нет', max_length=3, verbose_name='Признак просмотра'),
        ),
    ]
