# Generated by Django 2.1.2 on 2018-11-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayavka', '0003_zayavka_corpus'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='comnat',
            field=models.CharField(default='', max_length=55, verbose_name='Кол-во комнат:'),
        ),
        migrations.AddField(
            model_name='zayavka',
            name='kv_numb',
            field=models.IntegerField(default=0, verbose_name='№ квартиры'),
        ),
        migrations.AddField(
            model_name='zayavka',
            name='ploshad',
            field=models.IntegerField(default=0, verbose_name='Площадь квартиры:'),
        ),
        migrations.AddField(
            model_name='zayavka',
            name='stoimost',
            field=models.IntegerField(default=0, verbose_name='Стоимость квартиры:'),
        ),
    ]
