# Generated by Django 2.1.2 on 2018-11-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayavka', '0004_auto_20181108_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='ploshad',
            field=models.CharField(default=0, max_length=55, verbose_name='Площадь квартиры:'),
        ),
    ]
