# Generated by Django 2.1.2 on 2018-11-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayavka', '0005_auto_20181108_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='kv_numb',
            field=models.CharField(default=0, max_length=55, verbose_name='№ квартиры'),
        ),
    ]
