# Generated by Django 2.1.2 on 2018-11-10 09:37

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('zayavka', '0006_auto_20181109_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zayavka',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Ваш номер телефона:', max_length=128, verbose_name='Телефон:'),
        ),
    ]
