# Generated by Django 2.1.2 on 2018-11-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zayavka', '0008_auto_20181110_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zayavka',
            name='comnat',
        ),
        migrations.RemoveField(
            model_name='zayavka',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='zayavka',
            name='kv_numb',
        ),
        migrations.RemoveField(
            model_name='zayavka',
            name='ploshad',
        ),
        migrations.RemoveField(
            model_name='zayavka',
            name='prizn_pr',
        ),
        migrations.RemoveField(
            model_name='zayavka',
            name='stoimost',
        ),
    ]
