# Generated by Django 2.1.2 on 2018-11-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayavka', '0009_auto_20181110_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='budget',
            field=models.IntegerField(default=0, verbose_name=''),
        ),
    ]
