# Generated by Django 2.1.2 on 2018-11-12 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zayavka', '0011_auto_20181112_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zayavka',
            name='comment',
        ),
    ]
